const ActionType = {
    ADMIN: "ADMIN",
    PRODUCTS:"PRODUCTS",
    ORDERS: "ORDERS",
    EDITPRODUCT:"EDITPRODUCT",
    SHOWORDERDETAILS : "SHOWORDERDETAILS",
    ORDERDELIVERED : "ORDERDELIVERED",
    SELLER : "SELLER",
    LEFTBAR_TOGGLE:"LEFTBAR_TOGGLE"
}

export default ActionType;