const ActionType = {
    USER: "USER",
    CHANGE_PHONE: "CHANGE_PHONE",
    USERCART: "USERCART",
    PRODUCTS: "PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_TO_CART: "REMOVE_TO_CART",
    SIGNUP_DIALOG: "SIGNUP_DIALOG",
    SIGNUP_BTN: "SIGNUP_BTN",
    CATEGORY_TOGGLE: "CATEGORY_TOGGLE",
    CATEGORY: "CATEGORY",
    USERLOCALCART : "USERLOCALCART",
    EDIT_INFO:"EDIT_INFO",
    CART_TOGGLE:"CART_TOGGLE"
}

export default ActionType;