const ActionType = {
    ADMIN: "ADMIN",
    ALL_USER:"ALL_USER",
    PRODUCTS:"PRODUCTS",
    ORDERS: "ORDERS",
    EDITPRODUCT:"EDITPRODUCT",
    SHOWORDERDETAILS : "SHOWORDERDETAILS",
    ORDERDELIVERED : "ORDERDELIVERED",
    SELLER : "SELLER",
    CATEGORY:"CATEGORY",
    SUB_CATEGORY:"SUB_CATEGORY",
    LEFTBAR_TOGGLE:"LEFTBAR_TOGGLE"
}

export default ActionType;